<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Lider extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Lider_model');
    } 

    /*
     * Listing of lider
     */
    function index()
    {
        $data['lider'] = $this->Lider_model->get_all_lider();
        
        $data['_view'] = 'lider/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new lider
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'Nombre' => $this->input->post('Nombre'),
            );
            
            $lider_id = $this->Lider_model->add_lider($params);
            redirect('lider/index');
        }
        else
        {            
            $data['_view'] = 'lider/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a lider
     */
    function edit($idLider)
    {   
        // check if the lider exists before trying to edit it
        $data['lider'] = $this->Lider_model->get_lider($idLider);
        
        if(isset($data['lider']['idLider']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'Nombre' => $this->input->post('Nombre'),
                );

                $this->Lider_model->update_lider($idLider,$params);            
                redirect('lider/index');
            }
            else
            {
                $data['_view'] = 'lider/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The lider you are trying to edit does not exist.');
    } 

    /*
     * Deleting lider
     */
    function remove($idLider)
    {
        $lider = $this->Lider_model->get_lider($idLider);

        // check if the lider exists before trying to delete it
        if(isset($lider['idLider']))
        {
            $this->Lider_model->delete_lider($idLider);
            redirect('lider/index');
        }
        else
            show_error('The lider you are trying to delete does not exist.');
    }
    
}
