<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Equipo_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get equipo by idEquipo
     */
    function get_equipo($idEquipo)
    {
        return $this->db->get_where('equipos',array('idEquipo'=>$idEquipo))->row_array();
    }
        
    /*
     * Get all equipos
     */
    function get_all_equipos()
    {
        $this->db->select('*');
        $this->db->from('equipos');
        $this->db->join('lider', 'lider.idLider = equipos.idLider');
        return $this->db->get()->result_array();
    }
        
    /*
     * function to add new equipo
     */
    function add_equipo($params)
    {
        $this->db->insert('equipos',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update equipo
     */
    function update_equipo($idEquipo,$params)
    {
        $this->db->where('idEquipo',$idEquipo);
        return $this->db->update('equipos',$params);
    }
    
    /*
     * function to delete equipo
     */
    function delete_equipo($idEquipo)
    {
        return $this->db->delete('equipos',array('idEquipo'=>$idEquipo));
    }
}
