<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Lider_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get lider by idLider
     */
    function get_lider($idLider)
    {
        return $this->db->get_where('lider',array('idLider'=>$idLider))->row_array();
    }
        
    /*
     * Get all lider
     */
    function get_all_lider()
    {
        $this->db->order_by('idLider', 'desc');
        return $this->db->get('lider')->result_array();
    }
        
    /*
     * function to add new lider
     */
    function add_lider($params)
    {
        $this->db->insert('lider',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update lider
     */
    function update_lider($idLider,$params)
    {
        $this->db->where('idLider',$idLider);
        return $this->db->update('lider',$params);
    }
    
    /*
     * function to delete lider
     */
    function delete_lider($idLider)
    {
        return $this->db->delete('lider',array('idLider'=>$idLider));
    }
}
